version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=letmein
      - MYSQL_DATABASE=musik-datenbank
      - MYSQL_USER=user
    ports:
      - "3307:3307"
