version: '3'
services:
  mysql:
    image: mysql
    command: --max_allowed_packet=500000000
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: musicdb
    ports:
      - "3308:3306"