spring:
  datasource:
    url: jdbc:mysql://localhost:3308/testapp
    username: root
    password: helloworld
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/main.xml

