spring:
  datasource:
    url: jdbc:mysql://localhost:3308/musicdb
    username: root
    password: helloworld
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/main.xml
#    enabled: false
#  datasource:
#    url:  jdbc:mysql://localhost:3308/musicdb
#    username: root
#    password: helloworld
#    hikari:
#      connection-timeout: 10000
#      maximum-pool-size: 2
#      max-lifetime: 840000 # equals 14min (15min default max AWS token lifetime)
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  liquibase:
#    change-log: classpath:db/main.xml
#    enabled: false
#logging:
#  level:
#    root: trace
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
