spring:
  datasource:
    url: jdbc:mysql://localhost:3308/musicdb
    username: root
    password: helloworld
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/main.xml
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
