version: '3'
services:
  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:mysql://localhost:3307/db -schemas=myschema -user=root -password=letmein -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"