version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'USER_APP'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data.sql:/docker-entrypoint-initdb.d