version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://localhost:3307/db -schemas=myschema -user=root -password=letmein -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=letmein
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3307